library(XML)
library(ogbox)
library(affy)
library(dplyr)
library(magrittr)
# download stanley C cohort data
dir.create('data-raw/StanleyC/cels',recursive=TRUE, showWarnings = FALSE)
# autogenerated password that was sent to me in plaintext form. They obviously dont care enough to be actually secure
# so why should I. Replace with your 
system('wget --user OganM --password rMa3JbF4 https://www.stanleygenomics.org/stanley/standard/study_zips/study2_raw.zip -O data-raw/StanleyC/stanleyC.zip')
system('unzip data-raw/StanleyC/stanleyC.zip -d data-raw/StanleyC/cels')

ogbox::getGemmaAnnot('GPL570','data-raw/GemmaAnnots/GPL96',annotType='noParents')

system('wget --user OganM --password rMa3JbF4 https://www.stanleygenomics.org/stanley/standard/studyPatients.jsp?study_id=2 -O data-raw/StanleyC/metadata.html')
StanleyCMeta = readHTMLTable('data-raw/StanleyC/metadata.html')[[2]]

system('wget --user OganM --password rMa3JbF4 https://www.stanleygenomics.org/stanley/standard/studyQC.jsp?study_id=2 -O data-raw/StanleyC/qc.html')
StanleyCQC = readHTMLTable('data-raw/StanleyC/qc.html')[[1]]

cels= celFiles('data-raw/StanleyC/cels/',full.names=TRUE)
affy = ReadAffy(filenames = cels)
affy = affy::rma(affy)
affy = gemmaAnnot(affy, 'data-raw/GemmaAnnots/GPL96')

list[gene,exp] = sepExpr(affy)

affy %<>% mostVariable(threshold= exp %>% unlist %>% median,
                       threshFun=median)

list[gene,exp] = sepExpr(affy)

colnames(exp) = gsub('\\s.*$','',cn(exp))

rownames(exp) = gene$Gene.Symbol

StanleyCExp = exp

StanleyCExp = StanleyCExp[match(StanleyCMeta$Filename, cn(StanleyCExp))]

patients = StanleyCMeta$`Stanley ID` %>% unique


StanleyCExp = StanleyCExp[,cn(StanleyCExp) %in% StanleyCQC$Filename]
StanleyCMeta %<>% filter(Filename %in% StanleyCQC$Filename)



StanleyCExp = StanleyCExp[!cn(StanleyCExp) %in%  (StanleyCQC %>% filter(Outlier == 1) %$% Filename)]
StanleyCMeta = StanleyCMeta[!StanleyCMeta$Filename %in% (StanleyCQC %>% filter(Outlier == 1) %$% Filename),]  

devtools::use_data(StanleyCExp,overwrite=TRUE)
devtools::use_data(StanleyCMeta,overwrite=TRUE)

#'KDM5D' %in% rn(StanleyCExp)


#StanleyCExp['KDM5D',] %>% unlist %>% plot(col= StanleyCMeta$Sex %>% toColor %$% cols)
